name: CI Pokedex

on: [push, pull_request]

jobs:
  CI-Pokedex:
    runs-on: ubuntu-latest

    steps:
      # Check le repo Github
      - name: Github checkout
        uses: actions/checkout@v4

      # Setup Node.js avec la version 20 et utilise le cache de npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # Check les fichiers pour respecter TypeScript
      - name: Run TypeScript
        run: npx tsc --noEmit

      # Check les fichiers pour respecter Prettier
      - name: Run Prettier
        run: npx prettier --check .

      # Check les fichiers pour respecter ESLint
      - name: Run ESLint
        run: npx eslint .

        # Lancer le serveur local
      - name: Start server
        run: npm run start &
        env:
          NODE_ENV: test

      # Attendre que le serveur soit prêt
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      # Lancer les tests Cypress e2e
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: http://localhost:5173
          config-file: cypress.config.js

      # Build le projet
      - name: Build project
        run: npm run build

      # Print un message quand tout est Ok
      - name: Message de fin
        run: echo "🎉 Tout est Ok !"
