name: Pokedex CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript
        run: npx tsc --noEmit

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint .

      - name: Build project
        run: npm run build

      - name: Message de fin
        run: echo "🎉 Tout est Ok !"
